### ISSUE TITLE
Member Class

### ISSUE THREAD

**Issue by ghost** [ywang208/cs-8-first-project#20]
# User Story Points
- [ ] **Member Class Completed.**

> - Design a class to contain and manipulate the members data.
> - Create accessors and mutators

---
| **Member Class** |  **Functions description**  |
| --- | --- |
| **Membership Class** | **Class for members accessors and mutators to retrieve and send new data to Update Class** |
| *Member Name* | Accessor and mutator for the members name for both basic and preferred |
| *Member Phone* | Accessor and mutator for the members phone for both basic and preferred |
| *Membership type* | Boolean type : 0 - Basic Member & 1 - Preferred Member |
| *Member Expiration Date* | Date class to store all members date of expiration |
| *Member Amount Spent* | Accessor and mutator for the members amount spend for both basic and preferred  |
| *Member Amount Due* | Accessor and mutator for the members amount due for both basic and preferred  |
```c++
MembersClass(
         std::string name,          // INPUT/OUTPUT - Members name
         std::string phone,         // INPUT/OUTPUT - Members phone
         bool type,                 // INPUT/OUTPUT - Membership type (Basic/Preferred)
         Date _date,                // INPUT/OUTPUT - Members date
         double amount,             // INPUT/OUTPUT/CAL - Members amount spent
         double fees,               // INPUT/OUTPUT/CAL - Members amount due
         double rebate);            // INPUT/OUTPUT/CAL - Only preferred members rebate
```

---

---
## Tasks:
> @nickadel  - quit the job.

> @ywang208 - Designing GUI (user interface)

>  @dthai5 - ?

> @gnrmdz -  build the member class

---

**Comment by dthai5** [comment]
class Member
{
Public:
          //Accessors
          string getMemberName();
          string getMemberPhone();
          bool getMemberType();
          double getMemberExpDate();
          double getMemberAmountSpent();
          double getMemberAmountDue();

          //Mutators
          void setMemberName(string name);
          void setMemberPhone(string phone_number);
          void setMemberType(bool type);
          void setMemberExpDate(double date);
          void setMemberAmountSpent(double amount);
          void setMemberAmountDue(double fees);

Private:
         string memberName;
         string memberPhoneNum;
         bool memberType;
         double memberExpDate;
         double memberAmount;
         double memberFees;
}

Do you also want me to do the methods? Oh yeah I'm not sure if I did the boolean function to get member type correctly.

**Comment by dthai5** [comment]
Oh wait on Date _date, is Date a template?

**Comment by ghost** [comment]
hey can you text or call me 818-669-8451
