### ISSUE TITLE
Story Point

### ISSUE THREAD

**Issue by ghost** [ywang208/cs-8-first-project#21]
# User Story Points
- [ ] **Update Class Completed.**

> - Create a class to input a text file's data and output
> - Create linked list to store the data
> - Make sure there are no memory leak!

---
| **Member Class** |  **Functions description**  |
| --- | --- |
| **MemberList Class** (update class) | **Class to retrieve/store members data** |
| *Basic Members* | Get the members date, id, item name, item price, item quantity |
| *Preferred Members* | Get the members date, id, item name, item price, item quantity, rebate |
| *All Memberss* | Show all members, sorted, print by item, print yearly, search with month, (add/delete/create) |

```c++
template<typename M>
struct Members
{
    M data;
    Members *next;
    Members(M data) : data(data), next(NULL) {}
};

// membership container
template<typename M>
class MembersList
{
    Members<M>* head;
    Members<M>* tail;
    M count_helper(Members<M>* mPtr);
public:
    MembersList();
    MembersList(const MembersList& list);
//    MembersList(M name,         // Members name
//                M id,           // Members id
//                M mem_type,     // Membership type
//                M exp_date,     // Expiration date
//                M amount_spent, // Total amount spent
//                M rebate['P']); // Rebate - Preferred Members Only
    MembersList& operator=(const MembersList& list);
    ~MembersList();
    void push_back(const M& value);            // push_back function working properly
    void push_front(const M& value);           // push_front NEEDS TO TEST
    void pop_front() noexcept(false);          // pop_front NEEDS TO TEST
    void select_sort();                        // sort function working properly
    bool remove_member(const M& value);        // remove_member NEEDS TO FIXING
    // bool add_member(const M& value);        // add_member NEEDS TO BE STARTED
    bool isEmpty()const;                       // isEmpty NEEDS TO TEST
    std::string output_linkedlist();           // output_linkedlist is working properly
};

// Used as pointers in the WareHouseMembers.h (Qt Header File)
    MembersList<std::string>* members_date;
    MembersList<int>* members_id;
    MembersList<std::string>* members_items;
    MembersList<double>* items_price;
    MembersList<size_t>* items_quantity;
    MembersList<double>* preferred_rebate;
```
---

---
# Task:
> @gnrmdz - supported with research on how to input text file data onto linked list.
> @dthai5 - supported with research on how to input text file data onto linked list.
> @phildkim86 - main programmer with the support of @gnrmdz & @dthai5.
1. ~~Build a data structure container of a linked list to store data from text file.~~
2. ~~Figure how how to input text file data onto linked list container.~~
```
# STILL IN PROGRESS
3. Store each variable; date, id, item, price, quantity
   1. Date
   2. ID
   3. Item
   4. Price
   5. Quantity
4. Sort, remove, add, etc..
5. Print on command
6. Save Info

# ISSUES:
- Still having trouble storing into individual variables, why? Because we are using Qt library and not familiar with Qt functionalities.
```
> User story:
> “As Philip Kim, Genar Mendez and Daniel Thai, we want to establish the proper input storing of different variables from the text file so that we can output everything properly as demanded by the customer."
---

---
**CURRENT GUI (IN PROGRESS)**
![screen shot 2017-09-29 at 12 21 58 am](https://user-images.githubusercontent.com/12452646/31005149-513cfb96-a4ac-11e7-97bf-585c3f68fb69.png)

---

**Comment by dthai5** [comment]
http://www.informit.com/articles/article.aspx?p=1405549&seqNum=3
http://www.informit.com/articles/article.aspx?p=1405549&seqNum=5
those links are talking about separator directory

**Comment by dthai5** [comment]
http://doc.qt.io/qt-5/qprocess.html
another link to maybe separate variables 

Can you guys help with finding the actual code.. theres too much to read by my self.
