### ISSUE TITLE
Agile Story #1 (Product Owner & Scrum Master)

### ISSUE THREAD

**Issue by ghost** [ywang208/cs-8-first-project#24]
---
# Agile Story #1 (Product Owner & Scrum Master)
---

### WHAT NEEDS TO BE DONE (User Story):
**`“As a product owner and scrum master, before we can go through any process, we have to decide who the programmers are going to be, then I want to develop a program for members in a wholesale club. We have certain requirements that the customer is asking, include a container class with at least one overloaded operator. You should also describe the growth rate of the program to the customer. Include at least one pointer and 10 agile stories. Implementation will be decided upon the programmer; however, we must include the following: `**

---
> - Task 1: ~~**Allow user to enter membership number or name and get lost of the total purchases.**~~
> - Task 2: ~~**Allow user to enter item name and get the quantity of that item sold as well as the total price.**~~
> - Task 3: ~~**Allow user to enter in month and get a list of all members whose expiration date is that month and their amount due.**~~
> - Task 4: ~~**Allow user to add/delete members and also create a purchase for new members.**~~
> - Task 5: ~~**Implement an option for members to update to preferred type or downgrade to basic type.**~~
> - Task 6: ~~**Create an option of report to display list of items and quantities sold on that day with the name of the members. Also show the revenue for this given day. Include preferred/basic members.**~~
> - Task 7: ~~**Report that displays total purchases by all the members sorted by member id. Also include grand total.**~~
> - Task 8: ~~**Report that prints out the rebate of all the preferred members sorted by membership number.**~~
> - Task 9: ~~**Report that shows the amount per year paid by each member for the membership dues sorted by member type then by members name.**~~
> - Task 10: ~~**Include sales tax to %8.75. Include preferred membership fee $75.00. Include basic membership fee $60.00. Include preferred rebate %5.**~~
> - Task 10: ~~**Make sure to save all changes between executions.**~~
> - Story Point Estimation: 2
> - Story Point Priority: Medium-Low
> - Product Owner: @dthai5 
> - Scrum Master: ~~@nickadel~~, @phildkim86 
> - Programmers: @ywang208 @phildkim86 ~~@gnrmdz~~ 
---

### WHAT NEEDS TO BE DONE (User Story):
**`“After, design a UML Diagram that includes the following classes; MembersList, ItemList, PurchaseList, and TimeClass that will all connect together. Once the diagram is drawn, please report back to me with implementation of pseudo code within one week."`**

---
# UML DESIGN:
![java2](https://user-images.githubusercontent.com/12452646/31781178-a6601800-b4ac-11e7-9e72-d35fbc37997c.png)
---

### Definition of Done 
- [x] ~~Code produced that adheres to a coding standard Code commented~~
- [x] ~~Code checked into source control system~~
- [x] ~~Peer reviewed (or produced with pair programming) Unit tests written and passed~~
- [x] ~~Relevant documentation/diagrams produced and/or updated Product owner concurs~~
> Peer reviewed by: @ywang208 & @dthai5 

## PROBLEMS:
> - ### Scrum Master: @nickadel quit
> - ### Programmer: @gnrmdz quit

> ### Product Owner said,
**`"Well, the first meeting didn't go to well, I really hope these guys are capable of doing the job. 
But as now, we have decided that @ywang208, @phildkim86, and @gnrmdz will be the programmers and @dthai5 will be the scrum master/product owner. Initially, we couldn't decide on the UML Diagram and how the flow of the program was going to be because we couldn't decide on whether to use a vector or a linked list, but after serval meetings with the programmers, we have finally come to a conclusion is what I am hoping for."`**

**Comment by ywang208** [comment]
You are to write a program that services members of Wholesale Club.  You must use a container class with at least one overloaded operator.  You should also describe the growth rate of your program. At least one class must contain a pointer (a copy constructor needs to be written and tested).   Highlight the above.  Write at least 10 agile stories (including description, tasks, test scenarios, and story points) before you start to develop software.

Wholesale Club has two types of members: basic and preferred. 
Member information includes:
Name
Member number
Membership type
Membership expiration date
Total amount spent
Rebate amount (preferred members only)

A rebate of 5% of the total amount spent (not to include sales tax) is paid at the close of the year to the preferred members. Basic members pay annual dues of $60.00 and preferred members pay annual dues of $75.00. Your program will use the following files that will be provided:

A membership information file that will contain the member name, member number, membership type, and expiration date

Five sales files that contain details of member shopping for a day (member number, items purchased and prices - items not to exceed 100 on any given trip)

Your program should read from the daily sales file and update the members’ information accordingly. As the sales are processed, the total amount spent and rebate data for each member should be updated. Assume a sales tax rate of 8 3/4%.

Generate the following reports/request at any time:

1. A sales report for any given day. It should include a list of items and quantities sold on that day as well names of the members who shopped that day.  Report the total revenue for the given day.  It should also include number of preferred members and basic members who shopped during the given day.
2. A user should be able to enter a membership number or name and get a list of the total purchases per that member.
3. A report that prints the total purchases by all the members sorted by membership number.  It should also include a grand total of the purchases.
4. A user should be able to enter an item name and get the quantity of that item sold as well as the total sales price.
5. A report that prints out the quantity of each item sold sorted by item name.
6. A report that prints out the rebate of all the preferred members sorted by membership number.
7. A report showing the amount per year paid by each member for the membership dues sorted by member type (basic/preferred and then by member name.)
8. A user should be able to enter a month and get a list of all members whose memberships expire that month as well as their dues amount.
9. A user should be able to add/delete members.   Create purchases for the new members to validate your code.  Updates should be saved between executions.
10. Determine if any basic customer should convert their membership to preferred status.
11. Determine if any preferred customer should convert their membership to basic status.
Save all changes between executions.

A user should also be able to specify the above reports for basic members only, preferred members only, or all members.

Design a very readable, easy to use graphical interface to demonstrate your program.  Contingency handling should include addressing invalid input such as invalid membership number, invalid member type, invalid item name, etc.  All projects are due by October 20th.   No late projects will be accepted. Your team must demonstrate your project to me before it will be graded.   Each teammate must identify their accomplishments on the project.  

Submit an UML class diagram with your project.
