### ISSUE TITLE
Agile Story #2 (Developers)

### ISSUE THREAD

**Issue by ghost** [ywang208/cs-8-first-project#25]
---
# Agile Story #2 (Developers)
---

### WHAT NEEDS TO BE DONE (User Story):
**`"As a developer, to implement a this project, we find there are several thing we need to do followed by the requirement.
At first there are some nouns which are repeated several times. They are member, name, id, membership, membership fee, register date, month, purchase, item, price, amount for the order, amount for the sold in the history, spend, and rebate. And then, we think we can separate all these words in 3 main group, member, item, and purchase. Therefore, we can have 3 class about members list, purchases list, and items list to include every problem in the requirement,
Next we find, about the date, we can not do what we want efficiently with the basic library, so we also should create a new class named TimeRecord.
For now, we have already have 4 classes to solve all problems in these project. However we also need a main class or something else (just like the GUI) to help user to use our project. Totally, we should have 5 class or source file."`**

---
> - Story Point Estimation: 5
> - Story Point Priority: Medium-Low
> - Assignee:@phildkim86 @ywang208 
---

# UML DESIGN:
![java2](https://user-images.githubusercontent.com/12452646/31781178-a6601800-b4ac-11e7-9e72-d35fbc37997c.png)

### Definition of Done 
- [x] ~~Code produced that adheres to a coding standard Code commented~~
- [x] ~~Code checked into source control system~~
- [x] ~~Peer reviewed (or produced with pair programming) Unit tests written and passed~~
- [x] ~~Relevant documentation/diagrams produced and/or updated Product owner concurs~~
> Peer reviewed by: @ywang208 & @dthai5 @phildkim86

> ### Developer said,
`"As developers, we have decided the UML Diagram shown in the above image. We carefully thought out and draw out all the steps necessary steps needed to complete our tasks. Although it wasn't all that easy at first because both the programmers had different ideas on the approach and couldn't decide so easily. After serval meetings and drawing boards, we finally decided on the above flow of the program."`

**Comment by ywang208** [comment]
Developer Said:
As a developer, to implement a this project, we find there are several thing we need to do followed by the requirement.
At first there are some nouns which are repeated several times. They are member, name, id, membership,  membership fee, register date, month, purchase, item, price, amount for the order, amount for the sold in the history, spend, and rebate. And then, we think we can separate all these words in 3 main group, member, item, and purchase. Therefore, we can have 3 class about members list, purchases list, and items list to include every problem in the requirement,
Next we find, about the date, we can not do what we want efficiently with the basic library, so we also should create a new class named TimeRecord. 
For now, we have already have 4 classes to solve all problems in these project. However we also need a main class or something else (just like the GUI) to help user to use our project. Totally, we should have 5 class or source file.

Followed by what the developer said, there should be a UML like this :
![31781178-a6601800-b4ac-11e7-9e72-d35fbc37997c](https://user-images.githubusercontent.com/31906529/31808319-7c81f686-b527-11e7-81aa-d5b5059ec73a.png)
