### ISSUE TITLE
Agile Story #6 (Item Class Code)

### ISSUE THREAD

**Issue by ghost** [ywang208/cs-8-first-project#33]
---
# Agile Story #6 (Item Class Code)
---

## WHAT NEEDS TO BE DONE (User Story):
**`“As a programmer, I want to create a class about the items. It will include all the information about all item. First, there should be a structure about item, it will include item name, price, and the amount sold.
And then, there should be a function to sort the item's data in the list. Next, it should have a function to report the information about all items, return the information as a string. What's more, a function to return the price when user input the name is also necessary. Last, it can be update and store the information after a new purchase happen."`**

---
> - Story Point Estimation: 10
> - Story Point Priority: High-Low
> - Assignee: @ywang208 
> - Task 1: ~~Adding a new element in the lis.~~
> - Task 2: ~~Getting the price of the element,.~~
> - Task 3: ~~Getting the total information in the list.~~
> - Task 4: ~~Gteting the information about one item.~~
---

---
> ### For adding a new element in the list, we need to know the name and the price, and then add it in the list. The code is below:

```c++
void ItemList::addNew(string name, double price)
```
---

---
> ### For getting the price of the element, we need to get the name of the element as the parameter, and then use loop to search in the list, return the price. The code is below:

```c++
double ItemList::getPrice(string name)
```
---

---
> ### For getting the total information in the list, we need to declare an empty string, and then put the information from every element in the list together. The code is below:

```c++
string ItemList::totalInfo()
```
---

---
> ### For getting the information about one item, we need to get the name of the item as a parameter, and then find the stuff to return a string variable include the information about the item; if there is no such element as what the user want, return "This item is not exist!". The code is below:

```c++
string ItemList::itemInfo(string name)
```
---

### Definition of Done 
- [x] ~~Code produced that adheres to a coding standard Code commented~~
- [x] ~~Code checked into source control system~~
- [x] ~~Peer reviewed (or produced with pair programming) Unit tests written and passed~~
- [x] ~~Relevant documentation/diagrams produced and/or updated Product owner concurs~~
> Peer reviewed by: @ywang208 & @dthai5 

> ### Developer said,
`"This class is only about the item information.
Therefore, to test this class we can write a easy main class to know if this class is good."`

**Comment by ywang208** [comment]
Story Point Estimation: 10;
Story Priority: high
Assignee: @ywang208
List of task: short list

As a programmer, I want to create a class about the items. It will include all the information about all item. First, there should be a structure about item, it will include item name, price, and the amount sold.
And then, there should be a function to sort the item's data in the list. Next, it should have a function to report the information about all items, return the information as a string. What's more, a function to return the price when user input the name is also necessary. Last, it can be update and store the information after a new purchase happen.

For this part, the most important part are adding a new element in the list, return the price of the item, and return the information about the total information or the information about one element.

1.For adding a new element in the list, we need to know the name and the price, and then add it in the list. The code is below:
```c++
void ItemList::addNew(string name, double price)
{
    Item added(name, price);
    itemList.push_back(added);
    ++len;
    sortList();
}
```
2.For getting the price of the element, we need to get the name of the element as the parameter, and then use loop to search in the list, return the price. The code is below:
```c++
double ItemList::getPrice(string name)
{
    for(int i = 0; i < itemList.size(); ++i)
    {
        if (itemList[i].name == name)
            return itemList[i].price;
    }
    return 0;
}
```
3.For getting the total information in the list, we need to declare an empty string, and then put the information from every element in the list together. The code is below:
```c++
string ItemList::totalInfo()
{

    string result = "";
    string temp;
    stringstream ss;
    for(int i = 0; i < len; ++i)
    {
        ss << itemList[i].price;
        ss >> temp;
        ss.clear();
        result += itemList[i].name + "\n";
        result += temp + "\n";
        result += to_string(itemList[i].sold);
        if (i < len - 1)
            result += "\n";
    }
    return result;
}
```
4.For getting the information about one item, we need to get the name of the item as a parameter, and then find the stuff to return a string variable include the information about the item; if there is no such element as what the user want, return "This item is not exist!". The code is below:
```c++
string ItemList::itemInfo(string name)
{
    string result;
    // if it is exist
    if(itemExist(name))
    {
        // find the position of the item
        int pos = 0;
        for(; pos < len; ++pos)
        {
            if (itemList[pos].name == name)
                break;
        }
        stringstream ss;
        ss << (itemList[pos].sold * itemList[pos].price);
        string temp;
        ss >> temp;
        ss.clear();
        result = "Item:  " + name + "\nquantity:  " +
                to_string(itemList[pos].sold) + "\ntotal price:  " + temp;
    }
    else
        result = "This item is not exist!";
    return result;
}
```

Developer Said:
This class is only about the item information.
Therefore, to test this class we can write a easy main class to know if this class is good.
