### ISSUE TITLE
Agile Story #8 (Purchase Class Code)

### ISSUE THREAD

**Issue by ghost** [ywang208/cs-8-first-project#36]
---
# Agile Story #8 (Purchase Class Code)
---

## WHAT NEEDS TO BE DONE (User Story):
**`“As a programmer, I want to create a class about the purchase. It will include all the information about all purchase. First, there should be a structure about purchase, it will include date, id, item name, price, and the amount.
And then, there are 6 main functions included about the import purchase information, and report the information."`**

---
> - Story Point Estimation: 13
> - Story Point Priority: Medium-High
> - Assignee: @ywang208
> - Task 1: ~~Add purchase function.~~
> - Task 2: ~~Import the purchase information from the file.~~
> - Task 3: ~~Print one element in the list function.~~
> - Task 4: ~~Print the report for specific member.~~
> - Task 5: ~~Print the report for a given date.~~
> - Task 6: ~~Print all purchase out.~~
---

---
> ### In this function, the program can add a new purchase in a vector which store the purchase information. It should has price, item name, amount, customer id, item list, member list, and date information as parameters. And then generate a new purchase.

```c++
string PurchaseList::addPurchase(int id, string item, double price, int amount, MembersList &memberLyst, ItemList &itemLyst, string date)
```
---

---
> ### In this function, there should be a string variable about the file name and member list and itemlist as parameters. And then, use getline function get the information about the purchase and put it in the purchase list.

```c++
void PurchaseList::addPurchases(string pFile, MembersList &memberLyst, ItemList &itemsLyst)
```
---

---
> ### In this function, it will return the information about the specific purchase. It will include the date, id, item name, price and the amount. And the return type is the string.

```c++
string PurchaseList::printOneElement(Purchase *order)
```
---

---
> ### Print all purchase out.

```c++
string PurchaseList::reportForOneMember(int id)
```
---

---
> ### In this function, it will take a int variable which is about member id as the parameter, and return the information about the purchase form the member as a string type.
As a programmer, I will use loop to check each purchase, and find the information about the member id, and call printOneElement(Purchase *order) to put the information in a string which will be returned.

```c++
string PurchaseList::reportForOneMember(int id)
```
---

### Definition of Done 
- [x] ~~Code produced that adheres to a coding standard Code commented~~
- [x] ~~Code checked into source control system~~
- [x] ~~Peer reviewed (or produced with pair programming) Unit tests written and passed~~
- [x] ~~Relevant documentation/diagrams produced and/or updated Product owner concurs~~
> Peer reviewed by: @ywang208 & @dthai5 

> ### Developer said,
**`"In this function, the program can add a new purchase in a vector which store the purchase information. It should has price, item name, amount, customer id, item list, member list, and date information as parameters. And then generate a new purchase."`**

**Comment by ywang208** [comment]
Story Point Estimation: 13;
Story Priority: middle-high
Assignee: @ywang208
List of task: short list

As a programmer, I want to create a class about the purchase. It will include all the information about all purchase. First, there should be a structure about purchase, it will include date, id, item name, price, and the amount.
And then, there are 6 main functions included about the import purchase information, and report the information.
1.add purchase function
In this function, the program can add a new purchase in a vector which store the purchase information. It should has price, item name, amount, customer id, item list, member list, and date information as parameters. And then generate a new purchase.
```c++
string PurchaseList::addPurchase(int id, string item, double price, int amount,
                   MembersList &memberLyst, ItemList &itemLyst, string date)
{
    if(!memberLyst.isExist(id))
        return "the member is not exist";
    else
        memberLyst.changeSpend((price * amount* (1 + tax)), id);           // update the member list about the rebate and the spend
    if(itemLyst.itemExist(item))
        itemLyst.saleItem(item, amount);           // update itemlist
    else{
        itemLyst.addNew(item, price);           // add new element in the itemlist, and then update
        itemLyst.saleItem(item, amount);
    }
    // add a new purchase history
    Purchase *current = new Purchase(item, id, price, amount, date);
    current->next = head;
    head = current;
    ++count;
    return "Purchase Successfully!";
}
```
2.import the purchase information from the file:
in this function, there should be a string variable about the file name and member list and itemlist as parameters. And then, use getline function get the information about the purchase and put it in the purchase list.
```c++
void PurchaseList::addPurchases(string pFile, MembersList &memberLyst,
                                ItemList &itemsLyst)
{

    string temp;
    string date;
    int member_id;
    string itemName;
    double price;
    int quantity;
    stringstream ss;
    ifstream fin;
    fin.open(pFile.c_str());
    if(fin.good())
    {
        int counter = 0;
        while(getline(fin, temp))
        {
            counter %= 4;
            switch(counter)
            {
            // date
            case 0:
                date = temp;
                break;
            // id
            case 1:
                ss << temp;
                ss >> member_id;
                ss.clear();
                break;
            // item name
            case 2:
                itemName = temp;
                break;
            // price, quantity
            case 3:
                ss << temp;
                ss >> price;
                ss >> quantity;
                ss.clear();
                addPurchase(member_id, itemName, price, quantity,
                            memberLyst, itemsLyst, date);
                break;
            default:
                break;
            }
            ++counter;
        }
        fin.close();
    }
}
```
3.print one element in the list function
In this function, it will return the information about the specific purchase. It will include the date, id, item name, price and the amount. And the return type is the string.
```c++
string PurchaseList::printOneElement(Purchase *order)
{
    string result = "";
    string forPrice;
    stringstream ss;
    ss << order->price;
    ss >> forPrice;
    ss.clear();
    result += order->date.printDate() + "\n" + to_string(order->id) +
            "\n" + order->item + "\n" + forPrice +
            "\t" + to_string(order->amount);
    return result;
}
```
4.print the report for specific member
In this function, it will take a int variable which is about member id as the parameter, and return the information about the purchase form the member as a string type. 
As a programmer, I will use loop to check each purchase, and find the information about the member id, and call printOneElement(Purchase *order)  to put the information in a string which will be returned.
```c++
string PurchaseList::reportForOneMember(int id)
{
    Purchase *current = head;
    string result = "";

    for(int i = 0; i < count; ++i)
    {
        if(current->id == id)
            result += printOneElement(current) + "\n";
        current = current->next;
    }
    return result;
}
```
5.print the report for a given date
In this function, it will take a string variable about the date, and then find all the purchases which are happened in that day. After that, calculate the total purchase at that day, and how many purchases are about preferred member or basic member. Finally, print all these information as well as each purchase happened in that day.
```c++
string PurchaseList::reportForDate(string date, MembersList mlyst)
{
    Purchase *current = head;
    string result = "";
    string temp;
    int preferred = 0;
    int basic = 0;
    double total_spend = 0;
    for(int i = 0; i < count; ++i)
    {
        if(current->date.printDate() == date){
            result += printOneElement(current) + "\n";
            total_spend += current->amount * current->price * (1 + tax);
            if (mlyst[mlyst.getPos(current->id)].prefered)
                ++preferred;
            else
                ++basic;
        }
        current = current->next;
    }
    stringstream ss;
    ss<< total_spend;
    ss>>temp;
    ss.clear();

    result = "total spend is " + temp + ", and there are " + to_string(basic) + " basic members and "
            + to_string(preferred) + " members\n\n\n" + result;
    return result;
}
```
 6.print all purchase out
In this function, it will declare a empty string first, and then use loop to call printOneElement(Purchase *order) to add it in the string. After that, it will get a string which include all the purchase information.
```c++
string PurchaseList::printAllInfo()
{
    string result = "";
    Purchase *current = head;
    for(int i = 0; i < count; ++i , current = current->next){
        result += printOneElement(current) + "\n";
    }
    return result;
}
```
