### ISSUE TITLE
Agile Story #10 (Time Class Code)

### ISSUE THREAD

**Issue by ghost** [ywang208/cs-8-first-project#38]
---
# Agile Story #10 (Time Class Code)
---

## WHAT NEEDS TO BE DONE (User Story):
**`“As a programmer, I need to have a tool to store the time information, convert the information to the right string type(ex:MM/dd/yyyy), or when I input something, it can help me to generate a new data which stores the current time, and I also need a function which can help me to get the month information as an int.
For this TimeRecord class, the main purpose is to store the time information, convert the time type, and check when to get the current time. Therefore, there should be 5 very important functions in the TimeRecord class."`**

---
> - Story Point Estimation: 5
> - Story Point Priority: Low-High
> - Assignee: @ywang208 
> - Task 1: ~~Generate a new data store current time with no parameter.~~
> - Task 2: ~~Generate a new data with a string parameter.~~
> - Task 3: ~~Generate a new data with the 3 parameters about the month, day, and year.~~
> - Task 4: ~~Print the date information.~~
> - Task 5: ~~Get the Month information.~~
---

---
> **This one is the constructor with no parameter, it will use the time.h library to get the current time, and then store it in the data.**

```c++
TimeRecord::TimeRecord()
```
---

---
> **In this function, we need a right string type date value as a parameter, and then store the information to the new TimeRecord data.**

```c++
TimeRecord::TimeRecord(string dateInfo)
```
---

---
> **For the data constructor, user or the program may just give 3 numbers to generate a new date value. It will store the first parameter as the month, and then the second as the day, the third as the year.**

```c++
TimeRecord::TimeRecord(int d, int m, int y)
```
---

---
> **In this method, it will declare a new empty string "result", and then convert the month, day, and year information as the mm/dd/yyyy string type in the "result". Finally return the result;**

```c++
string TimeRecord::printDate()
```
---

---
> **In this method, the program will return the month value.**

```c++
int TimeRecord::getMonth()
```
---
---
# IMAGES OF USER INTERFACE:
![adobe spark](https://user-images.githubusercontent.com/12452646/31781192-b211e138-b4ac-11e7-96ab-05496b0a1499.jpg)
---

---
### Definition of Done 
- [x] ~~Code produced that adheres to a coding standard Code commented~~
- [x] ~~Code checked into source control system~~
- [x] ~~Peer reviewed (or produced with pair programming) Unit tests written and passed~~
- [x] ~~Relevant documentation/diagrams produced and/or updated Product owner concurs~~
> Peer reviewed by: @ywang208 & @dthai5 
---

> ### Developer said;
`"To test this class, we can write an easy main function to generate current time, and data with string variable or 3 int variable, and then print it out to check if the class runs well."`

**Comment by ywang208** [comment]
Story Point Estimation: 5;
Story Priority: low-middle
Assignee: @ywang208 
List of task: short list

As a programmer, I need to have a tool to store the time information, convert the information to the right string type(ex:MM/dd/yyyy), or when I input something, it can help me to generate a new data which stores the current time, and I also need a function which can help me to get the month information as an int.
For this TimeRecord class, the main purpose is to store the time information, convert the time type, and check when to get the current time. Therefore, there should be 5 very important functions in the TimeRecord class.

1.generate a new data store current time with no parameter
This one is the constructor with no parameter, it will use the time.h library to get the current time, and then store it in the data
```c++
TimeRecord::TimeRecord()
{
    // date type

    time_t current;
    struct tm *temp;
    stringstream ss;
    time(&current);
    temp = localtime(&current);

    ss << temp->tm_mday;
    ss >> date.day;
    ss.clear();

    ss << (temp->tm_mon + 1);
    ss >> date.month;
    ss.clear();

    ss << (temp->tm_year + 1900);
    ss >> date.year;
    ss.clear();
}
```
2.generate a new data with a string parameter
In this function, we need a right string type date value as a parameter, and then store the information to the new TimeRecord data. 
```c++
TimeRecord::TimeRecord(string dateInfo)
{
    // ex: 09/03/2013
    if (dateInfo.size() == 10){
        stringstream ss;
        ss << dateInfo.substr(0, 2);
        ss >> date.month;
        ss.clear();
        ss << dateInfo.substr(3, 2);
        ss >> date.day;
        ss.clear();
        ss << dateInfo.substr(6, 4);
        ss >> date.year;
        ss.clear();
    }
    // ex: ""
    else{
        time_t current;
        struct tm *temp;
        stringstream ss;
        time(&current);
        temp = localtime(&current);

        ss << temp->tm_mday;
        ss >> date.day;
        ss.clear();

        ss << (temp->tm_mon + 1);
        ss >> date.month;
        ss.clear();

        ss << (temp->tm_year + 1900);
        ss >> date.year;
        ss.clear();
    }
}
``` 
3.generate a new data with the 3 parameters about the month, day, and year
For the data constructor, user or the program may just give 3 numbers to generate a new date value. It will store the first parameter as the month, and then the second as the day, the third as the year.
```c++
TimeRecord::TimeRecord(int d, int m, int y)
{
    date.day = d;
    date.month = m;
    date.year = y;
}
```  
4.print the date information
In this method, it will declare a new empty string "result", and then convert the month, day, and year information as the mm/dd/yyyy string type in the "result". Finally return the result;
```c++
string TimeRecord::printDate()
{
    string result = "";
    stringstream ss;
    string temp;
    // month
    ss << date.month;
    ss >> temp;
    ss.clear();
    result += temp.size() == 1? "0" + temp + "/": temp + "/";
    // day
    ss << date.day;
    ss >> temp;
    ss.clear();
    result += temp.size() == 1? "0" + temp + "/": temp + "/";
    // year
    ss << date.year;
    ss >> temp;
    ss.clear();
    result += temp;
    return result;
}
```
5.get the Month information
In this method, the program will return the month value.
```c++
int TimeRecord::getMonth()
{
    return date.month;
}
```

Developer Said:
To test this class, we can write an easy main function to generate current time, and data with string variable or 3 int variable, and then print it out to check if the class runs well
