### ISSUE TITLE
get the quantity of the item sold function

### ISSUE THREAD

**Issue by ywang208** [ywang208/cs-8-first-project#8]
A user should be able to enter an item name and get the quantity of that item sold as well as the total sales price.

**Comment by nickadel** [comment]
Low Priority

Testing:
- Enter an item name.
- Ensure that the function returns the correct quantity of the item sold.
- Ensure that the function also returns the correct total sales for the item. 

Def. of Done:
When the function returns the correct quantity of items sold and also returns the correct item sales totals, which is the quantity multiplied by the item sell price.
